version: '3.5'
services:
  postgres:
    image: postgres:12
    ports:
      - "5455:5432"
    environment:
      POSTGRES_DB: "service"
      POSTGRES_USER: "service"
      POSTGRES_PASSWORD: "service"
    volumes:
      - ./src/main/resources/docker/:/docker-entrypoint-initdb.d/